// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTa5t5pAP74urpENahuN8X-qTEMP38h0',
    appId: '1:1023564792469:web:fb01ae798202353972919c',
    messagingSenderId: '1023564792469',
    projectId: 'fir-project-26eea',
    authDomain: 'fir-project-26eea.firebaseapp.com',
    storageBucket: 'fir-project-26eea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo1tzaY_S6RTwuPtyfwKadF3NqoCGLs90',
    appId: '1:1023564792469:android:0b29e58cd51490dc72919c',
    messagingSenderId: '1023564792469',
    projectId: 'fir-project-26eea',
    storageBucket: 'fir-project-26eea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHoybapoxVYCohsfc1K7bOFqzUSXT7ng',
    appId: '1:1023564792469:ios:20e3cad61d54a19872919c',
    messagingSenderId: '1023564792469',
    projectId: 'fir-project-26eea',
    storageBucket: 'fir-project-26eea.appspot.com',
    iosBundleId: 'com.example.flutterfirePrj',
  );
}
